# Generated by Django 4.2 on 2024-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_portfolio_is_active_project_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
